function [centers_droplet, ...
          radii_droplet, ...
          n_droplets] = find_droplets(im, expectedRadius, RadiusMargin, ...
                                      structure_element_size, ...
                                      binarization_sensitivity, ...
                                      imfindcircle_edge_threshold, ...
                                      imfindcircle_sensitivity)
%% find_droplets 
%Find whole droplets in a brightfield image.
% 
%   Usage 
% [centers_droplet, ...
%  radii_droplet, ...
%  n_droplets] = find_droplets(im, expectedRadius, RadiusMargin, ...
%                              structure_element_size, ...
%                              binarization_sensitivity, ...
%                              imfindcircle_edge_threshold, ...
%                              imfindcircle_sensitivity)
% 
%	INPUT 
% file: image file name
%**************** A COMPLETER
%  
%	OUTPUTS 
%**************** A COMPLETER
% 
%	EXAMPLES
% expectedRadius=35;
% RadiusMargin=[0.8 1.2];
% structure_element_size=2;
% binarization_sensitivity=0.533;
% imfindcircle_edge_threshold=0.01;
% imfindcircle_sensitivity=0.85;
% [centers_droplet, ...
%  radii_droplet, ...
%  n_droplets] = find_droplets(im, expectedRadius, RadiusMargin, ...
%                              structure_element_size, ...
%                              binarization_sensitivity, ...
%                              imfindcircle_edge_threshold, ...
%                              imfindcircle_sensitivity)
% 
%   AUTHOR : DIXNEUF Sophie, BIOASTER
%   CREATED : 2019-08-20
%--------------------------------------------------------------------------                                 
    imbin = imbinarize(im,'adaptive','ForegroundPolarity','dark','Sensitivity',binarization_sensitivity);
    se = strel('disk',structure_element_size);
    imbin = imopen(imbin,se);
    imbin = imclearborder(imbin);
    [centers_droplet, ...
     radii_droplet] = imfindcircles(imbin, round(expectedRadius*RadiusMargin),...
                                    'ObjectPolarity', 'bright', ...
                                    'EdgeThreshold',imfindcircle_edge_threshold, ...
                                    'Sensitivity',imfindcircle_sensitivity);
    n_droplets = length(radii_droplet);
end