function [overlay_fullname] = visualize_detected_droplets(im, folderesults, ...
                                                          field_number, ...
                                                          time_number, ...
                                                          centers_droplet, ...
                                                          radii_droplet, ...
                                                          n_droplets, ...
                                                          linewidth, ...
                                                          fontsize)
%% visualize_detected_droplets 
% Create and save an overlay png image of the original brightfield image
% and detected droplets
%**************** A COMPLETER
% 
%   Usage 
% [overlay_fullname] = visualize_detected_droplets(im, folderesults, ...
%                                                           field_number, ...
%                                                           time_number, ...
%                                                           centers_droplet, ...
%                                                           radii_droplet, ...
%                                                           n_droplets, ...
%                                                           linewidth, ...
%                                                           fontsize)
% 
%	INPUT 
%**************** A COMPLETER
%  
%	OUTPUTS 
% overlay_fullname: full name of the saved png overlay image
% 
%	EXAMPLES
% [overlay_fullname] = visualize_detected_droplets(im, folderesults, ...
%                                                           field_number, ...
%                                                           time_number, ...
%                                                           centers_droplet, ...
%                                                           radii_droplet, ...
%                                                           n_droplets, ...
%                                                           linewidth, ...
%                                                           fontsize)
% 
%   AUTHOR : DIXNEUF Sophie, BIOASTER
%   CREATED : 2019-08-20
%--------------------------------------------------------------------------
    figure;
    imagesc(im); axis image off; colormap gray;
    viscircles(centers_droplet, radii_droplet, 'EdgeColor', 'b', ...
               'LineStyle', '-', 'LineWidth', linewidth);
    hold on;
        for i_droplet=1:n_droplets
            text(centers_droplet(i_droplet,1), ...
                 centers_droplet(i_droplet,2), ...
                 num2str(i_droplet),'Color','r', ...
                 'FontSize',fontsize);
        end
    title(sprintf('%d detected drops - BF \n',n_droplets));
    hold off;
    supname=char(strcat('T', time_number, '_XY', field_number, '_detected_drops_BF'));
    overlay_fullname = fullfile(folderesults,supname);
    print(gcf, overlay_fullname, '-dpng','-r250');
    close;
end


